### ISSUE TITLE
[Feature request] A custom lint for enforcing documentation

### ISSUE THREAD

**Issue by literalEval** [fluttercandies/candies_analyzer_plugin#2]
### Platforms

dart, Android, iOS

### Description

Thanks for this awesome plugin. Can you make a custom lint rule that

1. Checks that each enum, class and its members etc have documentation
2. The documentation is in the right format according to DartDoc guidlines ?

### Why

I am working with a team of some people and wanted to enforce documentation check in the GitHub actions so that the contributors must add documentation for whatever new code they write.

If it is not possible for you to give time to this feature, then can you please get me in the right direction of making custom lint rules with `candies` so that I can try doing it myself ? Even if you can help me in getting to the 1st one (check for documentation), I'll try the 2nd one (right format of documentation) myself.

Thanks.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/candies_analyzer_plugin/blob/main/lib/src/error/lints/dart/perfer_doc_comments.dart  
https://github.com/fluttercandies/candies_analyzer_plugin/blob/main/lib/src/error/lints/dart/good_doc_comments.dart

i use those lints in my team

**Comment by zmtzawqlp** [comment]
in my option, [candies_analyzer_plugin](https://github.com/fluttercandies/candies_analyzer_plugin) is easy to custom your own rule lint, you can read lints in package, and try to write your own lint.

**Comment by literalEval** [comment]
Thanks a lot !!! These two will do. I just need one change that documentation for `constructors` is not required. How can I change that ?

What I am trying to ask is that I have an existing project and I installed `candies_analyzer` plugin in it and it works great out of the box. I just need one simple change which I know how to implement but how to do that without creating another project ? Like is it possible to achieve this by adding 1-2 new files in my existing project ?

Also, what I want is to run the analyzer in GitHub actions and have option to run on single or multiple files. How to achieve that ?

**Comment by zmtzawqlp** [comment]
(https://github.com/fluttercandies/candies_analyzer_plugin/blob/977a58cc77a487cab7d6ef84f1fc6d6f8ce9cb58/lib/src/error/lints/dart/perfer_doc_comments.dart#L224)

you should run plugin in debug.dart, and you will see all AST.

if you want to custom lint, you should to do as readme. follow analyzer_plugin rule to create a custom analyze as dart team.

**Comment by literalEval** [comment]
If I create a PR that removes documentation check for Constructors (as constructors don't really need to be documented normally), will it be merged ? This could be a feature improvement, don't you think ? @zmtzawqlp :)

**Comment by zmtzawqlp** [comment]
no, thanks, this plugin just want to teach people how to use it, it's easy to define custom lints by yourself. different team has different rules.

**Comment by literalEval** [comment]
Okay :)
Thanks a lot for answering all the queries. I'll let you know if I have any errors while setup.
